INCLUDE "sound_headers.asm"
INCLUDE "padding/L0D4BE9.asm"
INCLUDE "bgm/bgm_4a.asm"
INCLUDE "bgm/bgm_40.asm"
INCLUDE "bgm/bgm_3e.asm"
INCLUDE "bgm/bgm_0b.asm"
INCLUDE "bgm/bgm_0a.asm"
INCLUDE "bgm/bgm_09.asm"
INCLUDE "padding/L0E4000.asm"
INCLUDE "bgm/bgm_4b.asm"
INCLUDE "bgm/bgm_04.asm"
INCLUDE "bgm/bgm_08.asm"
INCLUDE "bgm/bgm_01.asm"
INCLUDE "bgm/bgm_02.asm"
INCLUDE "padding/L0E7F97.asm"
INCLUDE "padding/L0F4000.asm"

