Sound_SndHeaderPtrTable:
	dw SndHeader_BGM_01 ; $80
	dw SndHeader_BGM_02 ; $81
	dw SndHeader_BGM_03 ; $82
	dw SndHeader_BGM_04 ; $83
	dw SndHeader_BGM_05 ; $84
	dw SndHeader_BGM_06 ; $85
	dw SndHeader_BGM_07 ; $86
	dw SndHeader_BGM_08 ; $87
	dw SndHeader_BGM_09 ; $88
	dw SndHeader_BGM_0A ; $89
	dw SndHeader_BGM_0B ; $8A
	dw SndHeader_Pause ; $8B
	dw SndHeader_Unpause ; $8C
	dw SndHeader_SFX_0E ; $8D
	dw SndHeader_SFX_0F ; $8E
	dw SndHeader_SFX_10 ; $8F
	dw SndHeader_SFX_11 ; $90
	dw SndHeader_SFX_12 ; $91
	dw SndHeader_SFX_13 ; $92
	dw SndHeader_SFX_14 ; $93
	dw SndHeader_SFX_15 ; $94
	dw SndHeader_SFX_16 ; $95
	dw SndHeader_SFX_17 ; $96
	dw SndHeader_SFX_18 ; $97
	dw SndHeader_SFX_19 ; $98
	dw SndHeader_SFX_1A ; $99
	dw SndHeader_SFX_1B ; $9A
	dw SndHeader_SFX_1C ; $9B
	dw SndHeader_SFX_1D ; $9C
	dw SndHeader_SFX_1E ; $9D
	dw SndHeader_SFX_1F ; $9E
	dw SndHeader_SFX_20 ; $9F
	dw SndHeader_SFX_21 ; $A0
	dw SndHeader_SFX_22 ; $A1
	dw SndHeader_SFX_23 ; $A2
	dw SndHeader_SFX_24 ; $A3
	dw SndHeader_SFX_25 ; $A4
	dw SndHeader_SFX_26 ; $A5
	dw SndHeader_SFX_27 ; $A6
	dw SndHeader_SFX_28 ; $A7
	dw SndHeader_SFX_29 ; $A8
	dw SndHeader_SFX_2A ; $A9
	dw SndHeader_SFX_2B ; $AA
	dw SndHeader_SFX_2C ; $AB
	dw SndHeader_SFX_2D ; $AC
	dw SndHeader_SFX_2E ; $AD
	dw SndHeader_SFX_2F ; $AE
	dw SndHeader_SFX_30 ; $AF
	dw SndHeader_SFX_31 ; $B0
	dw SndHeader_SFX_32 ; $B1
	dw SndHeader_SFX_33 ; $B2
	dw SndHeader_SFX_34 ; $B3
	dw SndHeader_SFX_35 ; $B4
	dw SndHeader_SFX_36 ; $B5
	dw SndHeader_SFX_37 ; $B6
	dw SndHeader_SFX_38 ; $B7
	dw SndHeader_SFX_39 ; $B8
	dw SndHeader_SFX_3A ; $B9
	dw SndHeader_SFX_3B ; $BA
	dw SndHeader_BGM_01 ; $BB
	dw SndHeader_BGM_01 ; $BC
	dw SndHeader_BGM_3E ; $BD
	dw SndHeader_BGM_3F ; $BE
	dw SndHeader_BGM_40 ; $BF
	dw SndHeader_BGM_01 ; $C0
	dw SndHeader_BGM_01 ; $C1
	dw SndHeader_BGM_01 ; $C2
	dw SndHeader_BGM_01 ; $C3
	dw SndHeader_BGM_01 ; $C4
	dw SndHeader_BGM_01 ; $C5
	dw SndHeader_BGM_01 ; $C6
	dw SndHeader_BGM_01 ; $C7
	dw SndHeader_BGM_49 ; $C8
	dw SndHeader_BGM_4A ; $C9
	dw SndHeader_BGM_4B ; $CA
Sound_SndBankPtrTable:
	db BANK(SndHeader_BGM_01) ; $80
	db BANK(SndHeader_BGM_02) ; $81
	db BANK(SndHeader_BGM_03) ; $82
	db BANK(SndHeader_BGM_04) ; $83
	db BANK(SndHeader_BGM_05) ; $84
	db BANK(SndHeader_BGM_06) ; $85
	db BANK(SndHeader_BGM_07) ; $86
	db BANK(SndHeader_BGM_08) ; $87
	db BANK(SndHeader_BGM_09) ; $88
	db BANK(SndHeader_BGM_0A) ; $89
	db BANK(SndHeader_BGM_0B) ; $8A
	db BANK(SndHeader_Pause) ; $8B
	db BANK(SndHeader_Unpause) ; $8C
	db BANK(SndHeader_SFX_0E) ; $8D
	db BANK(SndHeader_SFX_0F) ; $8E
	db BANK(SndHeader_SFX_10) ; $8F
	db BANK(SndHeader_SFX_11) ; $90
	db BANK(SndHeader_SFX_12) ; $91
	db BANK(SndHeader_SFX_13) ; $92
	db BANK(SndHeader_SFX_14) ; $93
	db BANK(SndHeader_SFX_15) ; $94
	db BANK(SndHeader_SFX_16) ; $95
	db BANK(SndHeader_SFX_17) ; $96
	db BANK(SndHeader_SFX_18) ; $97
	db BANK(SndHeader_SFX_19) ; $98
	db BANK(SndHeader_SFX_1A) ; $99
	db BANK(SndHeader_SFX_1B) ; $9A
	db BANK(SndHeader_SFX_1C) ; $9B
	db BANK(SndHeader_SFX_1D) ; $9C
	db BANK(SndHeader_SFX_1E) ; $9D
	db BANK(SndHeader_SFX_1F) ; $9E
	db BANK(SndHeader_SFX_20) ; $9F
	db BANK(SndHeader_SFX_21) ; $A0
	db BANK(SndHeader_SFX_22) ; $A1
	db BANK(SndHeader_SFX_23) ; $A2
	db BANK(SndHeader_SFX_24) ; $A3
	db BANK(SndHeader_SFX_25) ; $A4
	db BANK(SndHeader_SFX_26) ; $A5
	db BANK(SndHeader_SFX_27) ; $A6
	db BANK(SndHeader_SFX_28) ; $A7
	db BANK(SndHeader_SFX_29) ; $A8
	db BANK(SndHeader_SFX_2A) ; $A9
	db BANK(SndHeader_SFX_2B) ; $AA
	db BANK(SndHeader_SFX_2C) ; $AB
	db BANK(SndHeader_SFX_2D) ; $AC
	db BANK(SndHeader_SFX_2E) ; $AD
	db BANK(SndHeader_SFX_2F) ; $AE
	db BANK(SndHeader_SFX_30) ; $AF
	db BANK(SndHeader_SFX_31) ; $B0
	db BANK(SndHeader_SFX_32) ; $B1
	db BANK(SndHeader_SFX_33) ; $B2
	db BANK(SndHeader_SFX_34) ; $B3
	db BANK(SndHeader_SFX_35) ; $B4
	db BANK(SndHeader_SFX_36) ; $B5
	db BANK(SndHeader_SFX_37) ; $B6
	db BANK(SndHeader_SFX_38) ; $B7
	db BANK(SndHeader_SFX_39) ; $B8
	db BANK(SndHeader_SFX_3A) ; $B9
	db BANK(SndHeader_SFX_3B) ; $BA
	db BANK(SndHeader_BGM_01) ; $BB
	db BANK(SndHeader_BGM_01) ; $BC
	db BANK(SndHeader_BGM_3E) ; $BD
	db BANK(SndHeader_BGM_3F) ; $BE
	db BANK(SndHeader_BGM_40) ; $BF
	db BANK(SndHeader_BGM_01) ; $C0
	db BANK(SndHeader_BGM_01) ; $C1
	db BANK(SndHeader_BGM_01) ; $C2
	db BANK(SndHeader_BGM_01) ; $C3
	db BANK(SndHeader_BGM_01) ; $C4
	db BANK(SndHeader_BGM_01) ; $C5
	db BANK(SndHeader_BGM_01) ; $C6
	db BANK(SndHeader_BGM_01) ; $C7
	db BANK(SndHeader_BGM_49) ; $C8
	db BANK(SndHeader_BGM_4A) ; $C9
	db BANK(SndHeader_BGM_4B) ; $CA
